development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  host: localhost
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  host: localhost
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: portfolio_production
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
